### ISSUE TITLE
ModernUI_CaptionBar in *.rc file

### ISSUE THREAD

**Issue by grog169** [mrfearless/ModernUI64#1]
ModernUI_CaptionBar in *.rc file only seem to work in x86. In x64 it compiles ok but when program runs it exit immediately as if MUICaptionBarRegister() does not register the class.

MUICaptionBarCreate() works fine.

**Comment by mrfearless** [comment]
Thanks, yes it appears there was a type in the classname (ModernUICaptionBar vs ModernUI_CaptionBar) which prevented the resource file creation of the control from working. 

Also just to note, the x64 version of ModernUI and its controls, lags behind from the development of the x86 version, so some features might not be included or not working correctly - dont have a c style header file created yet for this control if using with visual studio.

**Comment by grog169** [comment]
If your interested. Works fine on my end


#ifdef __cplusplus
extern "C" {
#endif

#ifdef _MSC_VER // MSVC compiler
#define MUI_EXPORT __declspec(dllexport) __stdcall
#else
#define MUI_EXPORT
#endif


//------------------------------------------------------------------------------
// ModernUI_CaptionBar Prototypes
//------------------------------------------------------------------------------

void MUI_EXPORT MUICaptionBarRegister();      // Use 'ModernUI_CaptionBar' as class in custom control
HWND MUI_EXPORT MUICaptionBarCreate(HWND hWndParent, LPCSTR *lpszCaptionText, DWORD64 dwCaptionHeight, DWORD64 dwResourceID, DWORD64 dwStyle);
unsigned int MUI_EXPORT MUICaptionBarSetProperty(HWND hModernUI_CaptionBar, DWORD64 dwProperty, DWORD64 dwPropertyValue);
unsigned int MUI_EXPORT MUICaptionBarGetProperty(HWND hModernUI_CaptionBar, DWORD64 dwProperty);
bool MUI_EXPORT MUICaptionBarLoadIcons(HWND hModernUI_CaptionBar, DWORD64 idResMin, DWORD64 idResMinAlt, DWORD64 idResMax, DWORD64 idResMaxAlt, DWORD64 idResRes, DWORD64 idResResAlt, DWORD64 idResClose, DWORD64 idResCloseAlt);
bool MUI_EXPORT MUICaptionBarLoadIconsDll(HWND hModernUI_CaptionBar, HINSTANCE hInstance, DWORD64 idResMin, DWORD64 idResMinAlt, DWORD64 idResMax, DWORD64 idResMaxAlt, DWORD64 idResRes, DWORD64 idResResAlt, DWORD64 idResClose, DWORD64 idResCloseAlt);
bool MUI_EXPORT MUICaptionBarLoadBackImage(HWND hModernUI_CaptionBar, DWORD64 dwImageType, DWORD64 dwResIDImage);


//------------------------------------------
// ModernUI_CaptionBar Styles
//------------------------------------------

#define MUICS_LEFT                                      0x0         // left align caption bar text
#define MUICS_CENTER                                0x1         // center align caption bar text
#define MUICS_NOMINBUTTON                0x2         // no minimize button
#define MUICS_NOMAXBUTTON                              0x4         // no maximize/restore button
#define MUICS_NOCLOSEBUTTON                           0x8         // no close button
#define MUICS_REDCLOSEBUTTON                         0x10       // close button uses win8+ red background color
#define MUICS_NOMOVEWINDOW                         0x20       // Dont allow window to move when caption bar is clicked and dragged, if not specified will allow this.
#define MUICS_WINNOMUISTYLE                            0x40       // Dont apply MUI borderless frame style to window/dialog, if not specified will apply MUI style.
#define MUICS_WINNODROPSHADOW                  0x80       // Dont apply drop shadow to window/dialog. If not specified will apply dropshadow if MUICS_WINDOWNOMUISTYLE not specified.
#define MUICS_USEICONSFORBUTTONS 0x100    // Use icons instead of text (Marlett font glyphs) for the min/max/res/close buttons: Load icons via the MUICaptionBarLoadIcons functions or set handles via @CaptionBarBtnIcoXXX properties
#define MUICS_KEEPICONS                                         0x200    // Dont delete icons handles when control is destoyed. Essential if icon handles are used in multiple controls or where set directly with properties
#define MUICS_NOCAPTIONTITLETEXT   0x400    // Dont draw a title text value, use lpszCaptionText for taskbar name of app only.

//------------------------------------------------------------------------------
// ModernUI_Caption Properties: Use with MUICaptionBarSetProperty /
// MUICaptionBarGetProperty or MUI_SETPROPERTY / MUI_GETPROPERTY msgs
//------------------------------------------------------------------------------
#define CaptionBarTextColor                      0              // RGBCOLOR. Text color for captionbar text and system buttons (min/max/restore/close)
#define CaptionBarTextFont                       8              // hFont. Font for captionbar text
#define CaptionBarBackColor                     16           // RGBCOLOR. Background color of captionbar and system buttons (min/max/restore/close)
#define CaptionBarBackImageType                         24           // DWORD64. Image Type - One of the following: MUICBIT_NONE,MUICBIT_BMP, MUICBIT_ICO, MUICBIT_PNG
#define CaptionBarBackImage                   32           // hImage. Image to display in captionbar background.
#define CaptionBarBackImageOffsetX    40           // DWORD64. Offset x +/- to set position of hImage. Default = 0
#define CaptionBarBackImageOffsetY     48           // DWORD64. Offset y +/- to set position of hImage. Default = 0
#define CaptionBarBtnTxtRollColor          56           // RGBCOLOR. Text color for system buttons (min/max/restore/close) when mouse moves over button
#define CaptionBarBtnBckRollColor         64           // RGBCOLOR. Background color for system buttons (min/max/restore/close) when mouse moves over button
#define CaptionBarBtnBorderColor          72           // RGBCOLOR. Border color for system buttons (min/max/restore/close). 0 = use same as CaptionBarBackColor
#define CaptionBarBtnBorderRollColor  80           // RGBCOLOR. Border color for system buttons (min/max/restore/close) when mouse moves over button. 0 = use CaptionBarBtnBckRollColor
#define CaptionBarBtnWidth                      88           // DWORD64. System buttons width. Defaults = 32px
#define CaptionBarBtnHeight                     96           // DWORD64. System buttons height. Defaults = 28px
#define CaptionBarBtnOffsetX                   104         // DWORD64. Offset y +/- to set position of system buttons (min/max/restore/close) in relation to right of captionbar
#define CaptionBarBtnOffsetY                   112         // DWORD64. Offset y + to set position of system buttons (min/max/restore/close) in relation to top of captionbar
#define CaptionBarBtnIcoMin                    120         // hIcon. For minimize button
#define CaptionBarBtnIcoMinAlt                              128         // hIcon. For minimize button when mouse moves over button
#define CaptionBarBtnIcoMax                   136         // hIcon. For maximize button
#define CaptionBarBtnIcoMaxAlt                              144         // hIcon. For maximize button when mouse moves over button
#define CaptionBarBtnIcoRes                     152         // hIcon. For restore button
#define CaptionBarBtnIcoResAlt                160         // hIcon. For restore button when mouse moves over button
#define CaptionBarBtnIcoClose                 168         // hIcon. For close button
#define CaptionBarBtnIcoCloseAlt            176         // hIcon. For close button when mouse moves over button
#define CaptionBarDllInstance                   184         // RGBCOLOR. If -1 = No painting of window/dialog background, handled by user or default system.
#define CaptionBarParam                                            192         // RGBCOLOR. If -1 = No border. if WindowBackColor != -1 then color of border to paint on window.


// CaptionBar Back Image Types
#define MUICBIT_NONE                                               0
#define MUICBIT_BMP                                  1
#define MUICBIT_ICO                                    2
#define MUICBIT_PNG                                  3

#ifdef __cplusplus
}
#endif

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mrfearless** [comment]
Thanks, I'll include that when I sync up with the x86 versions.

**Comment by grog169** [comment]
Love the fix. Works great.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
